### ISSUE TITLE
Differentiation between completed and non completed tasks

### ISSUE THREAD

**Issue by omargourari** [tmacwill/asana-client#13]
Just started using the client and I'm feeling that, maybe, being able to add a command option to being able to select completed and non completed tasks could be useful.

**Comment by gregglind** [comment]
perhaps stealing shamelessly from https://github.com/stephencelis/ghi for formatting and subcommands would be fruitful.

**Comment by dshack** [comment]
+1 here. I'd love to be able to type "asana/workspace" and see only to-dos, but instead it shows completed tasks as well.
