### ISSUE TITLE
Troubles when Project names have spaces

### ISSUE THREAD

**Issue by fortes** [tmacwill/asana-client#8]
Project named "My Project"

```
$ asana personal/my project
Task created in personal/my project!
```

Ends up making a new task called project, instead of listing. I tried using quotes, did not work either.

**Comment by wearethefoos** [comment]
This seems to work:

`$ asana 'Workspace/Project name with spaces' test due friday`

However: the name of the created task is not `test` (as I expected), but `Project name with spaces test` instead. It is due friday though :)

I will try to find the time te write a fix if that would help.
